r_hand:
  - urdf_file: "package://hrpsys_ros_bridge_tutorials/models/STARO.urdf"
    root_link: "RARM_LINK7"
    pose:
        position: {x: -0.0895, y: 0.0, z: 0.146}
        orientation: {x: -0.2706, y: 0.653281, z: 0.653281, w: -0.2706}
    # (setq trans (send (send *staro* :rarm :end-coords :copy-worldcoords) :transformation (send *staro* :rarm_link7_lk :copy-worldcoords) :local))

l_hand:
  - urdf_file: "package://hrpsys_ros_bridge_tutorials/models/STARO.urdf"
    root_link: "LARM_LINK7"
    pose:
        position: {x: -0.0895, y: 0.0, z: 0.146}
        orientation: {x: 0.2706, y: 0.653281, z: -0.653281, w: -0.2706}



