r_hand:
  - urdf_param: "/robot_description"
    root_link: "r_gripper_palm_link"
    pose:
        position: {x: -0.18, y: 0.0, z: 0.0}

l_hand:
  - urdf_param: "/robot_description"
    root_link: "l_gripper_palm_link"
    pose:
        position: {x: -0.18, y: 0.0, z: 0.0}
