# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
os: linux
dist: bionic  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email: true

env:
  global:
    - ROS_DISTRO=noetic
    - DOCKER_IMAGE=ros:noetic
    - UPSTREAM_WORKSPACE=https://github.com/rhaschke/python_qt_binding
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-strict-aliasing"
    - WARNINGS_OK=false
    - ABI_BASE_URL=https://ni.www.techfak.uni-bielefeld.de/abicheck/rviz-${ROS_DISTRO}.tar.gz

jobs:
  include:
    - env: TEST=catkin_lint,clang-format
    - env: TEST=abi,clang-tidy-fix
#    Unfortunately, BEFORE_SCRIPT is ran before rosdep and thus hasn't an effect
#    - env: BEFORE_SCRIPT="apt-get remove -q -y libogre-1.9.0v5; apt-get install -q -y libogre-1.12-dev"

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
