# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
language: generic
services:
  - docker

notifications:
  email:
    recipients:
      - bence.magyar.robotics@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  matrix:
    - ROS_DISTRO=noetic  ROS_REPO=ros
    - ROS_DISTRO=noetic  ROS_REPO=ros-testing
    - ROS_DISTRO=noetic  UPSTREAM_WORKSPACE='https://raw.githubusercontent.com/ros-controls/ros_control/$ROS_DISTRO-devel/ros_control.rosinstall -ros_controllers'

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
